### ISSUE TITLE
Can't run this extension in VS

### ISSUE THREAD

**Issue by rzinguer** [yagasoft/DynamicsCrm-PluginRegExtension#2]
[ERROR] Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at CrmPluginRegExt.VSPackage.Configuration.LoadSettings()
   at CrmPluginRegExt.VSPackage.Dialogs.Login..ctor(DTE2 dte)
   at CrmPluginRegExt.VSPackage.CrmPluginRegExt_VSPackagePackage.RegisterModifyPlugin(Project project)
   at CrmPluginRegExt.VSPackage.CrmPluginRegExt_VSPackagePackage.RegisterModifyPluginCallback(Object sender, EventArgs args)
Unable to register assembly, see error above.

**Comment by yagasoft** [comment]
This seems like a conflict with another extension.

- What is the version of Visual Studio you have?
- What other custom extensions do you have installed?

**Comment by rzinguer** [comment]
I have VS 2017, v. 15.9.24
Microsoft Visual Studio Test Platform

It looks like you did an update recently and you extension folder is missing Newtonsoft.Json.dll
I was able to mitigate the issue by placing missing dll in your extension folder.

**Comment by yagasoft** [comment]
Fixed issue by forcing manual binding in the code.
